### ISSUE TITLE
delete_objects_batch -> 'Access Denied'

### ISSUE THREAD

**Issue by hamann** [erlcloud/erlcloud#175] opened 2015-07-02 07:42 UTC
``` sh
iex(10)> :erlcloud_s3.delete_objects_batch(bucket,['ElixirCheat.pdf'])
{:ok,
 {[{'server', 'AmazonS3'}, {'transfer-encoding', 'chunked'},
   {'content-type', 'application/xml'}, {'connection', 'close'},
   {'date', 'Thu, 02 Jul 2015 07:35:56 GMT'},
   {'x-amz-request-id', 'D78FC7CCAB9ACF3D'},
   {'x-amz-id-2',
    'JN9sbL86DkIAF5SAqxikdlswepmrZoazvf5o/Vqxc+zXRmMzyOH9nxEI4ZwX2WCFDVUQa2qaXqk='}],
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<DeleteResult xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Error><Key>ElixirCheat.pdf</Key><Code>AccessDenied</Code><Message>Access Denied</Message></Error></DeleteResult>"}}
```

whereas deleting a single object works

``` sh
iex(12)> :erlcloud_s3.delete_object(bucket,'ElixirCheat.pdf')
[delete_marker: false, version_id: 'null']
```

Am I doing something wrong?

**Comment by JustMikey** [comment] 2015-11-30 13:57
+1

**Comment by motobob** [comment] 2016-03-30 22:30
true...issue confirmed. this is because `delete_objects_batch` is implemented badly and constructs wrong POST request and does not use generalised `s3_request`. 

this will be fixed in nearest versions.

**Closed** 2018-03-26 08:44 UTC
Labels: api, bug
