### ISSUE TITLE
Comments using # not allowed in .aws/credentials file

### ISSUE THREAD

**Issue by lehoff** [erlcloud/erlcloud#583] opened 2019-03-02 15:57 UTC
When using the normal # sign for comments in the `.aws/credentials` file `erlcloud_aws:profiles_parse/1` will fail with an error:

```
{{error,
                          {unable_to_parse_credential_file,
                              {error,
                                  {syntax_error,42,
                                      ["syntax error before: ",["\"#\""]]}}}},
```

The root cause of this is that `erlcloud_aws` uses `eini` to parse the credentials files, but ini files uses `;` (semi-colon) to comment out lines.

It is annoying not to be able to have comments in ones credentials file due to this.

**Comment by nalundgaard** [comment] 2019-03-02 19:07
I have a fix for this in erlcloud/eini, which is where the problem is. I’ll push it up later today.

**Comment by nalundgaard** [comment] 2019-03-02 22:01
@lehoff See erlcloud/eini#15 for the fix, I believe.

**Comment by lehoff** [comment] 2019-03-03 13:51
That should do the trick @nalundgaard  - thanks!

**Closed** 2019-03-04 09:38 UTC
